### ISSUE TITLE
Production?

### ISSUE THREAD

**Issue by madshargreave** [florinpatrascu/neo4j_sips#6]
Is it realistic to assume that this project could be used in production within the next couple of months?

**Comment by florinpatrascu** [comment]
I believe the `master` branch already is. It is simple, robust and gives you a decent level of integration between Elixir and a Neo4j remote server, over http. And unless there are bug reports for it, I am not planning to change much in this branch. 

What's your experience with the `master` branch, so far? 

My initial plan was to merge the `model_intro` dev branch into the `master`, and establish a baseline for Neo4j.Sips, but a couple of important things happened to Ecto and Neo4j which pushed my plans back:
- Ecto.Model's callbacks have been deprecated in favour of composing with changesets and of schema serializers
- Ecto.Model has been soft deprecated.
- and Bolt, Neo4j's upcoming binary protocol, is practically here

Basically I was contemplating a very large batch of changes to be made to the code currently in the `model_intro` dev branch, before being able to bring the Neo4j Models into the master. Still thinking about this, but most probably I'll stop developing on the `model_intro` dev branch and leave it as is, because it is stable and a few people are using it with some nice results. My current experimental work is in a new dev branch, where the focus is on implementing a Bolt compatible interface for Neo4j.Sips. The Neo4j.Sips models (with their callbacks replaced by changesets) will come after. A lot of work.    

My advise, use the master branch, and please let me know if you find any bugs. Feedback is highly appreciated. Thank you!

**Comment by madshargreave** [comment]
Hi

Thanks for the detailed reply, much appreciated.

I haven't yet had any practical experience with this repository yet, I am just in the initial phase of scouting and evaluating the available technologies and libraries.

This however sounds great, and I will definitely provide feedback when the project kicks off and I get hands-on experience with the master branch.

**Comment by florinpatrascu** [comment]
No problems at all. Thank you, for your interest.
